#!/usr/bin/env python3
"""Bundle the shared runtime into each independently installable CLI skill."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ("grok-cli", "antigravity-cli")
HEADER = "# Generated by scripts/sync_agent_runtime.py; edit scripts/agent_task_runtime.py.\n"


def sync(root: Path, check: bool = False) -> list[str]:
    expected = HEADER + (root / "scripts/agent_task_runtime.py").read_text(
        encoding="utf-8"
    )
    stale = []
    for name in SKILLS:
        target = root / "skills" / name / "scripts/agent_task_runtime.py"
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            stale.append(name)
            if not check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(expected, encoding="utf-8", newline="\n")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = sync(ROOT, args.check)
    if stale:
        print(
            ("Stale runtime copies: " if args.check else "Updated runtime copies: ")
            + ", ".join(stale)
        )
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
